apiVersion: apps/v1
kind: Deployment
metadata:
  name: stwo-web-stark
  namespace: stwo-web-stark
spec:
  selector:
    matchLabels:
      app: stwo-web-stark
  replicas: 1
  template:
    metadata:
      labels:
        app: stwo-web-stark
    spec:
      containers:
        - name: stwo-web-stark
          image: registry.internal.iosis.tech/stwo-web-stark
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: stwo-web-stark-service
  namespace: stwo-web-stark
spec:
  selector:
    app: stwo-web-stark
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stwo-web-stark-ingress
  namespace: stwo-web-stark
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx-ingress-prod
  tls:
    - hosts:
        - demo.stwo.iosis.tech
      secretName: stwo-web-stark-tls
  rules:
    - host: demo.stwo.iosis.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stwo-web-stark-service
                port:
                  number: 80
